"""Summarize revision execution status without importing training dependencies."""

from __future__ import annotations

import csv
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FINAL_DIR = ROOT / "outputs" / "final_tables"


def exists(rel_path: str) -> bool:
    return (ROOT / rel_path).exists()


def all_exist(paths: list[str]) -> bool:
    return all(exists(path) for path in paths)


def evidence(paths: list[str]) -> str:
    return "; ".join(path for path in paths if exists(path)) or "missing"


def markdown_table(rows: list[dict[str, str]], columns: list[str]) -> str:
    header = "| " + " | ".join(columns) + " |"
    divider = "| " + " | ".join("---" for _ in columns) + " |"
    body = []
    for row in rows:
        body.append("| " + " | ".join(row.get(column, "") for column in columns) + " |")
    return "\n".join([header, divider, *body]) + "\n"


def write_csv(path: Path, rows: list[dict[str, str]], columns: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=columns, extrasaction="ignore")
        writer.writeheader()
        writer.writerows(rows)


def row(
    task_id: str,
    phase: str,
    status: str,
    required_evidence: list[str],
    current_claim: str,
    next_action: str,
    stop_condition: str,
) -> dict[str, str]:
    evidence_present = "n/a"
    if required_evidence:
        evidence_present = "yes" if all_exist(required_evidence) else "partial"
    return {
        "task_id": task_id,
        "phase": phase,
        "status": status,
        "evidence_present": evidence_present,
        "evidence": evidence(required_evidence),
        "current_claim": current_claim,
        "next_action": next_action,
        "stop_condition": stop_condition,
    }


def main() -> None:
    rows = [
        row(
            "P0_RESULT_CONSOLIDATION",
            "Phase 0",
            "completed_analysis",
            [
                "outputs/final_tables/main_controlled_results.csv",
                "outputs/final_tables/main_controlled_results.md",
                "outputs/final_tables/claim_support_matrix.md",
                "outputs/final_tables/missing_artifacts.md",
            ],
            "Main controlled table supports UMS/schema as stable contributor; frozen-LM is not an external dominance claim.",
            "Use table in paper rewrite; do not fill missing NIH artifacts by guesswork.",
            "Stop if new rows lack checkpoint/config provenance.",
        ),
        row(
            "P0_COST_TABLE",
            "Phase 0",
            "completed_analysis_with_missing_fields",
            [
                "outputs/final_tables/cost_table.csv",
                "outputs/final_tables/cost_table.md",
                "outputs/final_tables/cost_missing_artifacts.md",
            ],
            "Deployment is LLM-free, but training-time frozen/random LM cost remains explicit and partly missing.",
            "Report unknown memory/param fields as missing unless logs/checkpoints prove them.",
            "Stop if training cost is summarized as resource-friendly without evidence.",
        ),
        row(
            "P1_FIELD_DIFFICULTY_ANALYSIS",
            "Phase 1",
            "completed_analysis",
            [
                "outputs/final_tables/per_field_results.csv",
                "outputs/final_tables/grouped_field_results.csv",
                "outputs/final_tables/field_difficulty_summary.md",
            ],
            "Frozen-LM gains are concentrated in rare/high-null/uncertain-heavy groups, not broad common-field dominance.",
            "Use as LLM-use-case evidence; do not treat it as full necessity proof.",
            "Stop if subgroup claims are made without per-field support.",
        ),
        row(
            "P3_ANSWERABILITY_SEMANTICS",
            "Phase 3",
            "completed_analysis_limited_by_oof",
            [
                "outputs/final_tables/answerability_semantics.csv",
                "outputs/final_tables/null_field_calibration.csv",
                "outputs/final_tables/answerability_semantics.md",
            ],
            "Null-as-negative does not invalidate answerability semantics, but calibration/failure claims need sample-level probabilities.",
            "Keep answerability claims semantic/protocol-level until OOF probabilities exist.",
            "Stop if null calibration is claimed from aggregate metrics only.",
        ),
        row(
            "P3_SCHEMA_DEPENDENCY_WRITEUP",
            "Phase 3",
            "completed_limitation_writeup",
            [
                "outputs/final_tables/schema_dependency_diagnostics.csv",
                "outputs/final_tables/schema_dependency_diagnostics.md",
                "outputs/final_tables/schema_dependency_case_study.md",
            ],
            "The current method depends strongly on fixed schema serialization; no schema-agnostic/paraphrase robustness claim.",
            "Use as limitation or appendix diagnostic.",
            "Stop if robustness language appears in main claim.",
        ),
        row(
            "P1_DATA_SCALING_PREP",
            "Phase 1",
            "config_ready",
            [
                "outputs/final_tables/data_scaling_prep_summary.md",
                "outputs/final_tables/data_scaling_config_validation.csv",
                "outputs/final_tables/data_scaling_run_order.md",
                "configs/data_scaling/frozen_lm_ums_1k.yaml",
                "configs/data_scaling/no_lm_ums_1k.yaml",
                "configs/data_scaling/bce_1k.yaml",
            ],
            "Patient-disjoint fixed split and config matrix are prepared; 1k BCE and no-LM source runs completed, frozen-LM preflight passed.",
            "Run the formal frozen-LM 1k source next; keep LP blocked until its source checkpoint exists.",
            "Stop if train/val patient overlap is nonzero or full matrix is launched at once.",
        ),
        row(
            "P1_DATA_SCALING_1K_BCE_DEBUG_ENTRY",
            "Phase 1",
            "debug_entry_passed_not_formal_result",
            [
                "outputs/data_scaling/bce_1k_seed900117/metrics_final.json",
                "outputs/data_scaling/bce_1k_seed900117/final.pt",
            ],
            "BCE 1k source entry can build dataloaders, load pretrained ViT, train/evaluate on CUDA, and exit cleanly in debug mode.",
            "Run the formal BCE 1k source only after a new execution-before record; do not treat debug metrics as paper evidence.",
            "Stop if debug outputs are mistaken for formal data-scaling results.",
        ),
        row(
            "P1_DATA_SCALING_1K_BCE_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run",
            [
                "outputs/data_scaling/bce_1k/metrics_final.json",
                "outputs/data_scaling/bce_1k/metrics_step_10000.json",
                "outputs/data_scaling/bce_1k/best.pt",
                "outputs/data_scaling/bce_1k/final.pt",
            ],
            "Formal BCE 1k source run completed on the fixed patient-disjoint split; it is a data-scaling control, not a historical main-table replacement.",
            "Start at most one next 1k source run after a fresh execution-before record; keep LP blocked until source checkpoints exist.",
            "Stop if fixed-split data-scaling metrics are mixed with historical P0 main-table metrics.",
        ),
        row(
            "P1_DATA_SCALING_1K_NO_LM_UMS_DEBUG_ENTRY",
            "Phase 1",
            "debug_entry_passed_not_formal_result",
            [
                "outputs/data_scaling/no_lm_ums_1k_seed900118/metrics_final.json",
                "outputs/data_scaling/no_lm_ums_1k_seed900118/final.pt",
            ],
            "no-LM UMS 1k source entry can build dataloaders, load pretrained ViT, train/evaluate on CUDA, and exit cleanly in debug mode.",
            "Use only the formal no-LM UMS 1k source run for fixed-split data-scaling claims.",
            "Stop if debug outputs are mistaken for formal data-scaling results.",
        ),
        row(
            "P1_DATA_SCALING_1K_NO_LM_UMS_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run",
            [
                "outputs/data_scaling/no_lm_ums_1k/metrics_final.json",
                "outputs/data_scaling/no_lm_ums_1k/metrics_step_10000.json",
                "outputs/data_scaling/no_lm_ums_1k/best.pt",
                "outputs/data_scaling/no_lm_ums_1k/final.pt",
            ],
            "Formal no-LM UMS 1k source run completed; under this fixed split it is weaker than BCE on binary metrics, while retaining nontrivial state accuracy.",
            "Run frozen-LM UMS 1k source next after debug/preflight to complete the 1k source triad.",
            "Stop if no-LM 1k is used as a global UMS failure claim or mixed with historical P0 rows.",
        ),
        row(
            "P1_DATA_SCALING_1K_FROZEN_LM_CACHE_PREFLIGHT",
            "Phase 1",
            "debug_entry_passed_qwen_cache_repaired",
            [
                "configs/data_scaling/frozen_lm_ums_1k.yaml",
                "outputs/data_scaling/frozen_lm_ums_1k_seed900119/checkpoints/best.pt",
                "outputs/data_scaling/frozen_lm_ums_1k_seed900119/checkpoints/step_5.pt",
                "outputs/data_scaling/frozen_lm_ums_1k_seed900119/checkpoints/final.pt",
            ],
            "Qwen 1.5B frozen-LM path loads and runs a 5-step debug entry; tiny-gpt2 debug failed because torch 2.5 cannot load unsafe .bin weights under current transformers.",
            "Write execution-before record for the formal frozen-LM UMS 1k source run and launch only that source run.",
            "Stop if formal run is treated as metric-complete before LP metrics exist.",
        ),
        row(
            "P1_DATA_SCALING_1K_FROZEN_LM_UMS_SOURCE_RUN",
            "Phase 1",
            "documented_early_stop_best_checkpoint_ready_for_lp",
            [
                "scripts/run_data_scaling_frozen_lm_ums_1k_source.cmd",
                "outputs/logs/data_scaling_frozen_lm_ums_1k_source.log",
                "outputs/data_scaling/frozen_lm_ums_1k/checkpoints/best.pt",
                "outputs/data_scaling/frozen_lm_ums_1k/checkpoints/step_1000.pt",
                "outputs/data_scaling/frozen_lm_ums_1k/checkpoints/step_2000.pt",
                "outputs/data_scaling/frozen_lm_ums_1k/checkpoints/step_3000.pt",
                "outputs/data_scaling/frozen_lm_ums_1k/checkpoints/step_4000.pt",
                "outputs/data_scaling/frozen_lm_ums_1k/checkpoints/step_5000.pt",
                "outputs/data_scaling/frozen_lm_ums_1k/checkpoints/step_6000.pt",
            ],
            "Formal frozen-LM UMS 1k source run was externally interrupted after step 6329; documented early-stop accepts checkpoints/best.pt because LP depends on best.pt and best val_loss was step 2000 at 0.0481.",
            "Use best.pt only with the documented early-stop provenance; proceed to frozen-LM 1k LP after a separate execution-before record.",
            "Stop if this interrupted source run is described as a normal completed source run or as having final.pt/EXITCODE 0.",
        ),
        row(
            "P1_DATA_SCALING_1K_FROZEN_LM_SOURCE_DECISION",
            "Phase 1",
            "completed_documented_early_stop",
            [
                "configs/data_scaling/lp_frozen_lm_ums_1k.yaml",
                "outputs/data_scaling/frozen_lm_ums_1k/checkpoints/best.pt",
            ],
            "LP config uses the frozen-LM source best.pt, so the interrupted source run can feed LP under an explicit early-stop rationale.",
            "Run LP debug/formal steps with this provenance boundary.",
            "Stop if downstream LP claims the source run completed normally.",
        ),
        row(
            "P1_DATA_SCALING_1K_FROZEN_LM_LP_DEBUG_ENTRY",
            "Phase 1",
            "debug_entry_passed_not_formal_result",
            [
                "outputs/data_scaling/lp_frozen_lm_ums_1k_seed900120/best.pt",
                "outputs/data_scaling/lp_frozen_lm_ums_1k_seed900120/step_20.pt",
                "outputs/data_scaling/lp_frozen_lm_ums_1k_seed900120/final.pt",
                "outputs/data_scaling/lp_frozen_lm_ums_1k_seed900120/metrics_final.json",
            ],
            "Frozen-LM 1k LP debug loaded 150 ViT params from source best.pt, froze the backbone, trained a 10,766-param head, and exited cleanly.",
            "Write execution-before record for the formal frozen-LM 1k LP run; do not treat debug metrics as paper evidence.",
            "Stop if debug metrics are mixed with formal 1k data-scaling results.",
        ),
        row(
            "P1_DATA_SCALING_1K_FROZEN_LM_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_data_scaling_lp_frozen_lm_ums_1k.cmd",
                "outputs/logs/data_scaling_lp_frozen_lm_ums_1k.log",
                "outputs/data_scaling/lp_frozen_lm_ums_1k/best.pt",
                "outputs/data_scaling/lp_frozen_lm_ums_1k/final.pt",
                "outputs/data_scaling/lp_frozen_lm_ums_1k/metrics_final.json",
                "outputs/data_scaling/lp_frozen_lm_ums_1k/metrics_step_400.json",
            ],
            "Formal frozen-LM 1k LP completed with EXITCODE 0; final macro_auc is 0.6894 and best-step-400 macro_auc is 0.7059.",
            "Run matched no-LM UMS 1k LP next before claiming frozen-LM low-data benefit.",
            "Stop if frozen-LM LP is compared to no-LM source metrics instead of matched LP metrics.",
        ),
        row(
            "P1_DATA_SCALING_1K_NO_LM_UMS_LP_DEBUG_ENTRY",
            "Phase 1",
            "debug_entry_passed_not_formal_result",
            [
                "outputs/data_scaling/lp_no_lm_ums_1k_seed900121/best.pt",
                "outputs/data_scaling/lp_no_lm_ums_1k_seed900121/step_20.pt",
                "outputs/data_scaling/lp_no_lm_ums_1k_seed900121/final.pt",
                "outputs/data_scaling/lp_no_lm_ums_1k_seed900121/metrics_final.json",
            ],
            "no-LM UMS 1k LP debug loaded 150 ViT params from source best.pt, froze the backbone, trained a 10,766-param head, and exited cleanly.",
            "Write execution-before record for the formal no-LM UMS 1k LP run; do not treat debug metrics as paper evidence.",
            "Stop if debug metrics are mixed with formal 1k data-scaling results.",
        ),
        row(
            "P1_DATA_SCALING_1K_NO_LM_UMS_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_data_scaling_lp_no_lm_ums_1k.cmd",
                "outputs/logs/data_scaling_lp_no_lm_ums_1k.log",
                "outputs/data_scaling/lp_no_lm_ums_1k/best.pt",
                "outputs/data_scaling/lp_no_lm_ums_1k/final.pt",
                "outputs/data_scaling/lp_no_lm_ums_1k/metrics_final.json",
                "outputs/data_scaling/lp_no_lm_ums_1k/metrics_step_200.json",
            ],
            "Formal no-LM UMS 1k LP completed with EXITCODE 0; final macro_auc is 0.7197 and best-step-200 macro_auc is 0.7170.",
            "Consolidate matched 1k LP results before running any larger scaling jobs.",
            "Stop if no-LM LP is confused with no-LM source-run metrics.",
        ),
        row(
            "P1_DATA_SCALING_1K_MATCHED_RESULT_CONSOLIDATION",
            "Phase 1",
            "completed_negative_macro_auc_for_frozen_lm",
            [
                "outputs/final_tables/data_scaling_1k_matched_summary.csv",
                "outputs/final_tables/data_scaling_1k_matched_summary.md",
                "outputs/final_tables/data_scaling_1k_matched_deltas.csv",
                "outputs/final_tables/data_scaling_1k_matched_deltas.md",
            ],
            "Matched 1k LP evidence is mixed: frozen-LM has small positive F1 deltas but lower macro-AUC than no-LM under final and best-val policies.",
            "Prefer schema-complexity/answerability-aware tests next; do not claim 1k low-data frozen-LM necessity.",
            "Stop if a paper table reports frozen-LM 1k as a broad win without metric-policy qualifiers.",
        ),
        row(
            "P1_DATA_SCALING_3K_BCE_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_control_only",
            [
                "scripts/run_data_scaling_bce_3k_source.cmd",
                "outputs/logs/data_scaling_bce_3k_source.log",
                "outputs/data_scaling/bce_3k/metrics_final.json",
                "outputs/data_scaling/bce_3k/metrics_step_1000.json",
                "outputs/data_scaling/bce_3k/best.pt",
                "outputs/data_scaling/bce_3k/final.pt",
                "outputs/final_tables/data_scaling_3k_bce_progress.csv",
                "outputs/final_tables/data_scaling_3k_bce_progress.md",
            ],
            "Formal BCE 3k source-control row completed with EXITCODE 0; best validation loss and best macro-AUC occur at step 1000, while final checkpoint has higher F1 but lower macro-AUC.",
            "Use only as a source-control row; 3k no-LM source is now the next completed source row, but LP/frozen-LM rows remain separate.",
            "Stop if the 3k BCE row is used as frozen-LM/no-LM scaling evidence or mixed with 1k LP claims.",
        ),
        row(
            "P1_DATA_SCALING_3K_NO_LM_UMS_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_source_only",
            [
                "scripts/run_data_scaling_no_lm_ums_3k_source_gpu0.cmd",
                "outputs/logs/data_scaling_no_lm_ums_3k_source_gpu0.log",
                "outputs/data_scaling/no_lm_ums_3k/metrics_final.json",
                "outputs/data_scaling/no_lm_ums_3k/metrics_step_1000.json",
                "outputs/data_scaling/no_lm_ums_3k/metrics_step_3000.json",
                "outputs/data_scaling/no_lm_ums_3k/best.pt",
                "outputs/data_scaling/no_lm_ums_3k/final.pt",
                "outputs/final_tables/data_scaling_3k_source_progress.csv",
                "outputs/final_tables/data_scaling_3k_source_progress.md",
            ],
            "Formal no-LM UMS 3k source row completed with EXITCODE 0; final macro_auc is 0.6668, best-loss step is 1000, and best-AUC step is 3000.",
            "Use this only as source provenance; the dependent 3k no-LM LP is now complete and reported separately.",
            "Stop if this source row is compared directly to 1k LP rows or described as a completed matched 3k result.",
        ),
        row(
            "P1_DATA_SCALING_3K_NO_LM_UMS_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_data_scaling_lp_no_lm_ums_3k_gpu0.cmd",
                "outputs/logs/data_scaling_lp_no_lm_ums_3k_gpu0.log",
                "outputs/data_scaling/lp_no_lm_ums_3k/metrics_final.json",
                "outputs/data_scaling/lp_no_lm_ums_3k/metrics_step_200.json",
                "outputs/data_scaling/lp_no_lm_ums_3k/best.pt",
                "outputs/data_scaling/lp_no_lm_ums_3k/final.pt",
                "outputs/final_tables/data_scaling_3k_no_lm_lp_progress.csv",
                "outputs/final_tables/data_scaling_3k_current_progress.csv",
            ],
            "Formal no-LM UMS 3k LP completed with EXITCODE 0; final macro_auc is 0.7342 and best-step-200 macro_auc is 0.7607.",
            "Use together with the completed 3k frozen-LM LP row for matched 3k LP interpretation; do not compare LP metrics to source loss.",
            "Stop if no-LM LP is compared to frozen-LM source loss or treated as full matched 3k evidence.",
        ),
        row(
            "P1_DATA_SCALING_3K_FROZEN_LM_UMS_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_source_loss_only",
            [
                "scripts/run_data_scaling_frozen_lm_ums_3k_source_gpu0.cmd",
                "outputs/logs/data_scaling_frozen_lm_ums_3k_source_gpu0.log",
                "outputs/data_scaling/frozen_lm_ums_3k/checkpoints/best.pt",
                "outputs/data_scaling/frozen_lm_ums_3k/checkpoints/final.pt",
                "outputs/data_scaling/frozen_lm_ums_3k/checkpoints/step_10000.pt",
                "outputs/final_tables/data_scaling_3k_source_progress.csv",
                "outputs/final_tables/data_scaling_3k_current_progress.csv",
            ],
            "Formal frozen-LM UMS 3k source row completed with EXITCODE 0; best source val_loss is 0.0410 at step 2500 and final val_loss is 0.1011.",
            "Use as source provenance only; matched 3k LP evidence is reported in the dependent LP row.",
            "Stop if source val_loss is compared directly to LP macro-AUC/F1 or used as a completed LP substitute.",
        ),
        row(
            "P1_DATA_SCALING_3K_FROZEN_LM_UMS_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_data_scaling_lp_frozen_lm_ums_3k_gpu0.cmd",
                "outputs/logs/data_scaling_lp_frozen_lm_ums_3k_gpu0.log",
                "outputs/data_scaling/lp_frozen_lm_ums_3k/metrics_final.json",
                "outputs/data_scaling/lp_frozen_lm_ums_3k/metrics_step_1600.json",
                "outputs/data_scaling/lp_frozen_lm_ums_3k/metrics_step_2800.json",
                "outputs/data_scaling/lp_frozen_lm_ums_3k/best.pt",
                "outputs/data_scaling/lp_frozen_lm_ums_3k/final.pt",
                "outputs/final_tables/data_scaling_3k_current_progress.csv",
            ],
            "Formal frozen-LM UMS 3k LP completed with EXITCODE 0; final macro_auc is 0.7449, best-AUC step 1600 macro_auc is 0.7505, and best-val step 2800 macro_auc is 0.7441.",
            "Report the matched 3k LP comparison as small final macro-AUC support for frozen-LM but not broad low-data necessity, because 1k remains mixed/negative and no-LM has the higher 3k best-AUC checkpoint.",
            "Stop if this single 3k final-AUC delta is generalized into a 500x or broad frozen-LM necessity claim.",
        ),
        row(
            "P1_DATA_SCALING_10K_BCE_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_control_only",
            [
                "scripts/run_data_scaling_bce_10k_source_gpu0.cmd",
                "outputs/logs/data_scaling_bce_10k_source_gpu0.log",
                "outputs/data_scaling/bce_10k/metrics_final.json",
                "outputs/data_scaling/bce_10k/metrics_step_2000.json",
                "outputs/data_scaling/bce_10k/metrics_step_3500.json",
                "outputs/data_scaling/bce_10k/best.pt",
                "outputs/data_scaling/bce_10k/final.pt",
                "outputs/final_tables/data_scaling_10k_progress.csv",
                "outputs/final_tables/data_scaling_10k_progress.md",
            ],
            "Formal BCE 10k source-control row completed with EXITCODE 0; final macro_auc is 0.7092, best-loss step 2000 macro_auc is 0.7434, and best-AUC step 3500 macro_auc is 0.7573.",
            "Use only as a 10k source-control row; no-LM/frozen-LM 10k source+LP rows remain required for matched 10k evidence.",
            "Stop if the 10k BCE row is used as matched no-LM/frozen-LM evidence or if final overfitting is hidden.",
        ),
        row(
            "P1_DATA_SCALING_10K_NO_LM_UMS_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_checkpoint_for_lp",
            [
                "scripts/run_data_scaling_no_lm_ums_10k_source_gpu0.cmd",
                "outputs/logs/data_scaling_no_lm_ums_10k_source_gpu0.log",
                "outputs/data_scaling/no_lm_ums_10k/metrics_final.json",
                "outputs/data_scaling/no_lm_ums_10k/metrics_step_2000.json",
                "outputs/data_scaling/no_lm_ums_10k/metrics_step_2500.json",
                "outputs/data_scaling/no_lm_ums_10k/best.pt",
                "outputs/data_scaling/no_lm_ums_10k/final.pt",
                "outputs/final_tables/data_scaling_10k_progress.csv",
                "outputs/final_tables/data_scaling_10k_progress.md",
            ],
            "Formal no-LM UMS 10k source row completed with EXITCODE 0; final macro_auc is 0.6616, best-loss step 2500 macro_auc is 0.7195, and best-AUC step 2000 macro_auc is 0.7242.",
            "Use as the source checkpoint required by lp_no_lm_ums_10k; it is not a matched LP result and should not be compared directly against LP macro-AUC rows.",
            "Stop if this source row is used as completed 10k no-LM LP evidence or if final overfitting is hidden.",
        ),
        row(
            "P1_DATA_SCALING_10K_NO_LM_UMS_LP_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_data_scaling_lp_no_lm_ums_10k_gpu0.cmd",
                "outputs/logs/data_scaling_lp_no_lm_ums_10k_gpu0.log",
                "outputs/data_scaling/lp_no_lm_ums_10k/metrics_final.json",
                "outputs/data_scaling/lp_no_lm_ums_10k/metrics_step_2800.json",
                "outputs/data_scaling/lp_no_lm_ums_10k/best.pt",
                "outputs/data_scaling/lp_no_lm_ums_10k/final.pt",
                "outputs/final_tables/data_scaling_10k_progress.csv",
                "outputs/final_tables/data_scaling_10k_progress.md",
            ],
            "Formal no-LM UMS 10k LP row completed with EXITCODE 0; final macro_auc is 0.7715 and best-loss step 2800 macro_auc is 0.7722.",
            "Use as the completed 10k no-LM LP branch; matched 10k frozen-LM source+LP remains required before making a 10k frozen-vs-no-LM conclusion.",
            "Stop if this no-LM LP result is treated as frozen-LM evidence or if it is mixed with source-classifier metrics.",
        ),
        row(
            "P1_DATA_SCALING_10K_FROZEN_LM_UMS_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_source_loss_only",
            [
                "scripts/run_data_scaling_frozen_lm_ums_10k_source_gpu0.cmd",
                "outputs/logs/data_scaling_frozen_lm_ums_10k_source_gpu0.log",
                "outputs/data_scaling/frozen_lm_ums_10k/checkpoints/best.pt",
                "outputs/data_scaling/frozen_lm_ums_10k/checkpoints/final.pt",
                "outputs/data_scaling/frozen_lm_ums_10k/checkpoints/step_10000.pt",
                "outputs/final_tables/data_scaling_frozen_source_progress.csv",
                "outputs/final_tables/data_scaling_frozen_source_progress.md",
            ],
            "Formal frozen-LM UMS 10k source row completed with EXITCODE 0; best source val_loss is 0.0392 at step 5000 and final val_loss is 0.0466.",
            "Use as source provenance for lp_frozen_lm_ums_10k only; it is not a downstream LP macro-AUC/F1 result.",
            "Stop if source val_loss is compared directly to LP macro-AUC/F1 or used as completed frozen-LM LP evidence.",
        ),
        row(
            "P1_DATA_SCALING_10K_FROZEN_LM_UMS_LP_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_data_scaling_lp_frozen_lm_ums_10k_gpu0.cmd",
                "outputs/logs/data_scaling_lp_frozen_lm_ums_10k_gpu0.log",
                "outputs/data_scaling/lp_frozen_lm_ums_10k/metrics_final.json",
                "outputs/data_scaling/lp_frozen_lm_ums_10k/metrics_step_1600.json",
                "outputs/data_scaling/lp_frozen_lm_ums_10k/best.pt",
                "outputs/data_scaling/lp_frozen_lm_ums_10k/final.pt",
                "outputs/final_tables/data_scaling_10k_progress.csv",
                "outputs/final_tables/data_scaling_10k_progress.md",
            ],
            "Formal frozen-LM UMS 10k LP row completed with EXITCODE 0; final macro_auc is 0.7778 and best-AUC step 1600 macro_auc is 0.7916.",
            "Use as the completed matched 10k frozen-LM LP branch; compare to no-LM 10k LP with metric-policy qualifiers.",
            "Stop if this LP result is mixed with source-loss metrics or generalized to 30k before the 30k frozen-LM branch completes.",
        ),
        row(
            "P1_DATA_SCALING_30K_BCE_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_control_only",
            [
                "scripts/run_data_scaling_bce_30k_source_gpu1.cmd",
                "outputs/logs/data_scaling_bce_30k_source_gpu1.log",
                "outputs/data_scaling/bce_30k/metrics_final.json",
                "outputs/data_scaling/bce_30k/metrics_step_7000.json",
                "outputs/data_scaling/bce_30k/best.pt",
                "outputs/data_scaling/bce_30k/final.pt",
                "outputs/final_tables/data_scaling_30k_progress.csv",
                "outputs/final_tables/data_scaling_30k_progress.md",
            ],
            "Formal BCE 30k source-control row completed with EXITCODE 0; final macro_auc is 0.7899, best-loss step 7000 macro_auc is 0.7858, and the named 30k split contains 29000 train records.",
            "Use only as a 30k source-control row; 30k no-LM/frozen-LM rows remain required for matched 30k evidence.",
            "Stop if the 30k BCE row is used as matched no-LM/frozen-LM evidence or if the 29000-record split size is hidden.",
        ),
        row(
            "P1_DATA_SCALING_30K_NO_LM_UMS_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_checkpoint_for_lp",
            [
                "scripts/run_data_scaling_no_lm_ums_30k_source_gpu1.cmd",
                "outputs/logs/data_scaling_no_lm_ums_30k_source_gpu1.log",
                "outputs/data_scaling/no_lm_ums_30k/metrics_final.json",
                "outputs/data_scaling/no_lm_ums_30k/metrics_step_7500.json",
                "outputs/data_scaling/no_lm_ums_30k/best.pt",
                "outputs/data_scaling/no_lm_ums_30k/final.pt",
                "outputs/final_tables/data_scaling_30k_progress.csv",
                "outputs/final_tables/data_scaling_30k_progress.md",
            ],
            "Formal no-LM UMS 30k source row completed with EXITCODE 0; final macro_auc is 0.7141, best-loss step 7500 macro_auc is 0.7353, and the named 30k split contains 29000 train records.",
            "Use as the source checkpoint required by lp_no_lm_ums_30k; it is not a matched LP result and should not be compared directly against LP macro-AUC rows.",
            "Stop if this source row is used as completed 30k no-LM LP evidence or if the 29000-record split size is hidden.",
        ),
        row(
            "P1_DATA_SCALING_30K_NO_LM_UMS_LP_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_data_scaling_lp_no_lm_ums_30k_gpu1.cmd",
                "outputs/logs/data_scaling_lp_no_lm_ums_30k_gpu1.log",
                "outputs/data_scaling/lp_no_lm_ums_30k/metrics_final.json",
                "outputs/data_scaling/lp_no_lm_ums_30k/metrics_step_2000.json",
                "outputs/data_scaling/lp_no_lm_ums_30k/best.pt",
                "outputs/data_scaling/lp_no_lm_ums_30k/final.pt",
                "outputs/final_tables/data_scaling_30k_progress.csv",
                "outputs/final_tables/data_scaling_30k_progress.md",
            ],
            "Formal no-LM UMS 30k LP row completed with EXITCODE 0; final macro_auc is 0.8150, best-loss step 2000 macro_auc is 0.8106, and the named 30k split contains 29000 train records.",
            "Use as the completed 30k no-LM LP branch; matched 30k frozen-LM source+LP remains required before making a 30k frozen-vs-no-LM conclusion.",
            "Stop if this no-LM LP result is treated as frozen-LM evidence or if the 29000-record split size is hidden.",
        ),
        row(
            "P1_DATA_SCALING_30K_FROZEN_LM_UMS_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_source_loss_only",
            [
                "scripts/run_data_scaling_frozen_lm_ums_30k_source_gpu1.cmd",
                "outputs/logs/data_scaling_frozen_lm_ums_30k_source_gpu1.log",
                "outputs/data_scaling/frozen_lm_ums_30k/checkpoints/best.pt",
                "outputs/data_scaling/frozen_lm_ums_30k/checkpoints/final.pt",
                "outputs/data_scaling/frozen_lm_ums_30k/checkpoints/step_10000.pt",
                "outputs/final_tables/data_scaling_frozen_source_progress.csv",
                "outputs/final_tables/data_scaling_frozen_source_progress.md",
            ],
            "Formal frozen-LM UMS 30k source row completed with EXITCODE 0; named 30k split contains 29000 train records, best source val_loss is 0.0361 at step 9500, and final val_loss is 0.0364.",
            "Use as source provenance for lp_frozen_lm_ums_30k only; it is not a downstream LP macro-AUC/F1 result.",
            "Stop if source val_loss is compared directly to LP macro-AUC/F1 or used as completed frozen-LM LP evidence.",
        ),
        row(
            "P1_DATA_SCALING_30K_FROZEN_LM_UMS_LP_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_data_scaling_lp_frozen_lm_ums_30k_gpu0.cmd",
                "outputs/logs/data_scaling_lp_frozen_lm_ums_30k_gpu0.log",
                "outputs/data_scaling/lp_frozen_lm_ums_30k/metrics_final.json",
                "outputs/data_scaling/lp_frozen_lm_ums_30k/metrics_step_800.json",
                "outputs/data_scaling/lp_frozen_lm_ums_30k/best.pt",
                "outputs/data_scaling/lp_frozen_lm_ums_30k/final.pt",
                "outputs/final_tables/data_scaling_30k_progress.csv",
                "outputs/final_tables/data_scaling_30k_progress.md",
            ],
            "Formal frozen-LM UMS 30k LP row completed with EXITCODE 0; final macro_auc is 0.8011, best-val step 2800 macro_auc is 0.8044, and best-AUC step 800 macro_auc is 0.8171.",
            "Use as the completed matched 30k frozen-LM LP branch; compare to no-LM 30k LP with metric-policy qualifiers.",
            "Stop if this LP result is mixed with source-loss metrics or if the 29000-record split size is hidden.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_SWEEP_PREP",
            "Phase 1",
            "frozen_lm_config_ready_no_lm_deferred",
            [
                "outputs/final_tables/schema_complexity_prep.md",
                "outputs/final_tables/schema_complexity_support_matrix.csv",
                "outputs/final_tables/schema_sweep_config_manifest.csv",
                "outputs/final_tables/schema_sweep_config_prep.md",
                "outputs/final_tables/no_lm_schema_sweep_config_manifest.csv",
                "outputs/final_tables/no_lm_schema_sweep_config_prep.md",
                "configs/schema_sweep/frozen_lm_s1_state_only.yaml",
                "configs/schema_sweep/frozen_lm_s2_state_answerability.yaml",
                "configs/schema_sweep/frozen_lm_s3_state_uncertainty.yaml",
                "configs/schema_sweep/no_lm_s1_state_only.yaml",
                "configs/schema_sweep/no_lm_s2_state_answerability.yaml",
                "configs/schema_sweep/no_lm_s3_state_uncertainty.yaml",
            ],
            "Frozen-LM S1/S2/S3 configs and no-LM S1/S2/S3 explicit-head source/LP configs exist on the fixed split.",
            "Use debug evidence to decide the first formal schema source run; do not launch the whole S1/S2/S3 matrix.",
            "Stop if config-ready rows are treated as completed formal schema-sweep performance.",
        ),
        row(
            "P1_SCHEMA_SWEEP_DEBUG_MODEL_CONFIG_FIX",
            "Phase 1",
            "completed_config_fix",
            [
                "configs/schema_sweep/frozen_lm_s1_state_only.yaml",
                "configs/schema_sweep/frozen_lm_s2_state_answerability.yaml",
                "configs/schema_sweep/frozen_lm_s3_state_uncertainty.yaml",
                "scripts/prepare_schema_sweep_configs.py",
            ],
            "Schema-sweep frozen-LM debug configs now use Qwen for debug mode, avoiding the known tiny-gpt2 unsafe .bin loading failure.",
            "Use these configs for single debug entries only; do not start full S1/S2/S3 sweep as a batch.",
            "Stop if debug mode silently falls back to tiny-gpt2.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_S2_FROZEN_LM_DEBUG_ENTRY",
            "Phase 1",
            "debug_entry_passed_serializer_validated",
            [
                "outputs/schema_sweep/frozen_lm_s2_state_answerability_seed900122/checkpoints/best.pt",
                "outputs/schema_sweep/frozen_lm_s2_state_answerability_seed900122/checkpoints/step_5.pt",
                "outputs/schema_sweep/frozen_lm_s2_state_answerability_seed900122/checkpoints/final.pt",
            ],
            "S2 state_answerability frozen-LM debug ran 5 steps with Qwen and confirmed target_json includes answerable fields.",
            "Run at most S3 state_uncertainty debug next, or design no-LM S2/S3 comparator before formal claims.",
            "Stop if S2 debug is treated as formal schema-complexity evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_S3_FROZEN_LM_DEBUG_ENTRY",
            "Phase 1",
            "debug_entry_passed_serializer_validated",
            [
                "outputs/schema_sweep/frozen_lm_s3_state_uncertainty_seed900123/checkpoints/best.pt",
                "outputs/schema_sweep/frozen_lm_s3_state_uncertainty_seed900123/checkpoints/step_5.pt",
                "outputs/schema_sweep/frozen_lm_s3_state_uncertainty_seed900123/checkpoints/final.pt",
            ],
            "S3 state_uncertainty frozen-LM debug ran 5 steps with Qwen and confirmed target_json includes uncertain fields.",
            "Design no-LM S2/S3 comparator or label future schema work as frozen-LM-only serialization diagnostics.",
            "Stop if S3 debug is treated as formal schema-complexity evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_COMPARATOR_DESIGN_AUDIT",
            "Phase 1",
            "explicit_head_design_ready_debug_required",
            [
                "scripts/train_ums_classifier.py",
                "scripts/prepare_no_lm_schema_sweep_configs.py",
                "outputs/final_tables/no_lm_schema_comparator_design.csv",
                "outputs/final_tables/no_lm_schema_comparator_design.md",
                "outputs/final_tables/no_lm_schema_sweep_config_manifest.csv",
            ],
            "no-LM S2/S3 now has an explicit auxiliary-head design and configs; legacy derived diagnostics remain a separate boundary.",
            "Run/debug explicit-head S2/S3 before any formal schema-complexity claim.",
            "Stop if derived diagnostics are described as equivalent to explicit-head S2/S3 training.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_DERIVED_METRIC_EXPORT",
            "Phase 1",
            "completed_validation_only_export",
            [
                "scripts/evaluate_no_lm_schema_derivatives.py",
                "outputs/final_tables/no_lm_schema_derivative_metrics.csv",
                "outputs/final_tables/no_lm_schema_derivative_metrics.md",
                "outputs/final_tables/no_lm_schema_derivative_per_label.csv",
                "outputs/final_tables/no_lm_schema_derivative_manifest.json",
            ],
            "no-LM answerability/uncertainty can be measured as validation-only derived diagnostics from an existing 4-state checkpoint.",
            "Use these as legacy derived-diagnostic baselines alongside explicit-head debug evidence; do not report them as formal explicit-head performance.",
            "Stop if these derived metrics are reported as explicit no-LM S2/S3 schema serialization training.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_EXPLICIT_HEADS_DEBUG",
            "Phase 1",
            "debug_entry_passed_explicit_heads_not_formal",
            [
                "scripts/train_ums_classifier.py",
                "scripts/prepare_no_lm_schema_sweep_configs.py",
                "configs/schema_sweep/no_lm_s2_state_answerability.yaml",
                "configs/schema_sweep/no_lm_s3_state_uncertainty.yaml",
                "outputs/schema_sweep/no_lm_s2_state_answerability_seed900124/best.pt",
                "outputs/schema_sweep/no_lm_s2_state_answerability_seed900124/final.pt",
                "outputs/schema_sweep/no_lm_s2_state_answerability_seed900124/metrics_final.json",
                "outputs/schema_sweep/no_lm_s3_state_uncertainty_seed900125/best.pt",
                "outputs/schema_sweep/no_lm_s3_state_uncertainty_seed900125/final.pt",
                "outputs/schema_sweep/no_lm_s3_state_uncertainty_seed900125/metrics_final.json",
            ],
            "no-LM S2 answerability and S3 uncertainty auxiliary heads pass 20-step debug entries and export auxiliary metrics.",
            "Superseded by completed formal no-LM S1/S2/S3 source+LP rows; keep debug metrics as runtime support only.",
            "Stop if debug rows are reported as formal no-LM S2/S3 performance or if the full schema matrix is launched at once.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_S2_FORMAL_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run",
            [
                "scripts/run_schema_no_lm_s2_source_resume4_gpu0.cmd",
                "outputs/logs/schema_no_lm_s2_source_resume4_gpu0.log",
                "outputs/schema_sweep/no_lm_s2_state_answerability/metrics_final.json",
                "outputs/schema_sweep/no_lm_s2_state_answerability/best.pt",
                "outputs/schema_sweep/no_lm_s2_state_answerability/final.pt",
                "outputs/schema_sweep/no_lm_s2_state_answerability/step_10000.pt",
            ],
            "Formal no-LM S2 state_answerability source run completed with EXITCODE 0; final answerability_macro_auc is 0.735958 and final state macro_auc is 0.715499.",
            "Run the dependent S2 LP only after a fresh execution-before record; use source best.pt/final.pt provenance explicitly.",
            "Stop if this source endpoint is described as a completed matched schema sweep or as LP evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_S3_FORMAL_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run",
            [
                "scripts/run_schema_no_lm_s3_source_resume3_gpu0.cmd",
                "outputs/logs/schema_no_lm_s3_source_resume3_gpu0.log",
                "outputs/schema_sweep/no_lm_s3_state_uncertainty/metrics_final.json",
                "outputs/schema_sweep/no_lm_s3_state_uncertainty/best.pt",
                "outputs/schema_sweep/no_lm_s3_state_uncertainty/final.pt",
                "outputs/schema_sweep/no_lm_s3_state_uncertainty/step_10000.pt",
            ],
            "Formal no-LM S3 state_uncertainty source run completed with EXITCODE 0; final uncertainty_macro_auc is 0.690307, while default-threshold uncertainty positives remain rare.",
            "Run the dependent S3 LP only after a fresh execution-before record; report ranking/calibration boundary.",
            "Stop if this source endpoint is described as a completed matched schema sweep or as LP evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_S2_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_schema_lp_no_lm_s2_gpu0.cmd",
                "outputs/logs/schema_lp_no_lm_s2_gpu0.log",
                "outputs/schema_sweep/lp_no_lm_s2_state_answerability/metrics_final.json",
                "outputs/schema_sweep/lp_no_lm_s2_state_answerability/best.pt",
                "outputs/schema_sweep/lp_no_lm_s2_state_answerability/final.pt",
                "outputs/schema_sweep/lp_no_lm_s2_state_answerability/step_3000.pt",
            ],
            "Formal no-LM S2 LP completed with EXITCODE 0; final macro_auc is 0.828866, best-loss step 2800 macro_auc is 0.831034, and best-AUC step 400 macro_auc is 0.847098.",
            "Use as no-LM S2 source+LP evidence; compare to frozen-LM only after matched frozen-LM S2 source+LP rows exist.",
            "Stop if S2 LP metrics are merged with 12-label source metrics or described as frozen-LM matched evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_S3_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_schema_lp_no_lm_s3_gpu1.cmd",
                "outputs/logs/schema_lp_no_lm_s3_gpu1.log",
                "outputs/schema_sweep/lp_no_lm_s3_state_uncertainty/metrics_final.json",
                "outputs/schema_sweep/lp_no_lm_s3_state_uncertainty/best.pt",
                "outputs/schema_sweep/lp_no_lm_s3_state_uncertainty/final.pt",
                "outputs/schema_sweep/lp_no_lm_s3_state_uncertainty/step_3000.pt",
            ],
            "Formal no-LM S3 LP completed with EXITCODE 0; final macro_auc is 0.815002, best-loss step 2800 macro_auc is 0.819476, and best-AUC step 400 macro_auc is 0.844872.",
            "Use as no-LM S3 source+LP evidence; matched frozen-LM S3 source+LP is recorded separately.",
            "Stop if S3 LP metrics are merged with 12-label source metrics or described as frozen-LM matched evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_S1_COVERAGE_AUDIT",
            "Phase 1",
            "completed_audit_s1_not_exactly_covered",
            [
                "scripts/audit_schema_s1_coverage.py",
                "outputs/final_tables/schema_s1_coverage_audit.csv",
                "outputs/final_tables/schema_s1_coverage_audit.md",
            ],
            "Historical S1-like no-LM/frozen-LM rows do not exactly cover formal fixed-split schema-sweep S1 because train/val content hashes differ; frozen-LM historical source final.pt is also missing.",
            "Keep S1 as a formal fixed-split gap unless scoped out or rerun under data/splits.",
            "Stop if historical main-table rows are used as exact S1 schema-sweep evidence without mismatch caveat.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_S1_FORMAL_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run",
            [
                "scripts/run_schema_no_lm_s1_source_gpu0.cmd",
                "outputs/logs/schema_no_lm_s1_source_gpu0.log",
                "outputs/schema_sweep/no_lm_s1_state_only/metrics_final.json",
                "outputs/schema_sweep/no_lm_s1_state_only/best.pt",
                "outputs/schema_sweep/no_lm_s1_state_only/final.pt",
                "outputs/schema_sweep/no_lm_s1_state_only/step_10000.pt",
            ],
            "Formal no-LM S1 state_only source run completed with EXITCODE 0; final macro_auc is 0.713327, best-loss step 7500 macro_auc is 0.735068, and best-AUC step 5500 macro_auc is 0.744081.",
            "Run the dependent S1 LP only after a fresh execution-before record; keep S1 source separate from S2/S3 auxiliary-head metrics.",
            "Stop if this source endpoint is described as completed S1 LP evidence or matched frozen-LM/no-LM schema sweep evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_NO_LM_S1_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_schema_lp_no_lm_s1_gpu0.cmd",
                "outputs/logs/schema_lp_no_lm_s1_gpu0.log",
                "outputs/schema_sweep/lp_no_lm_s1_state_only/metrics_final.json",
                "outputs/schema_sweep/lp_no_lm_s1_state_only/best.pt",
                "outputs/schema_sweep/lp_no_lm_s1_state_only/final.pt",
                "outputs/schema_sweep/lp_no_lm_s1_state_only/step_3000.pt",
            ],
            "Formal no-LM S1 LP completed with EXITCODE 0; final macro_auc is 0.821601, best-loss step 2000 macro_auc is 0.820109, and best-AUC step 400 macro_auc is 0.850335.",
            "Use as no-LM S1 source+LP evidence; compare to frozen-LM only after matched frozen-LM S1 source+LP rows exist.",
            "Stop if S1 LP metrics are merged with 12-label source metrics or described as frozen-LM matched evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_FROZEN_LM_S1_FORMAL_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run",
            [
                "scripts/run_schema_frozen_lm_s1_source_gpu0.cmd",
                "scripts/summarize_frozen_lm_source_training.py",
                "outputs/logs/schema_frozen_lm_s1_source_gpu0.log",
                "outputs/final_tables/frozen_lm_source_training_summary.csv",
                "outputs/final_tables/frozen_lm_source_val_loss_trace.csv",
                "outputs/schema_sweep/frozen_lm_s1_state_only/checkpoints/best.pt",
                "outputs/schema_sweep/frozen_lm_s1_state_only/checkpoints/final.pt",
                "outputs/schema_sweep/frozen_lm_s1_state_only/checkpoints/step_10000.pt",
            ],
            "Formal frozen-LM S1 state_only source run completed with EXITCODE 0; checkpoint best_val_loss is 0.035434 at step 9000, and final/step_10000 checkpoints are complete.",
            "Run the dependent S1 LP only after a fresh execution-before record; do not report source loss as downstream LP/classification evidence.",
            "Stop if this source checkpoint is reported as downstream LP/classification evidence or if best-at-9000 is mistaken for an incomplete run.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_FROZEN_LM_S1_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_schema_lp_frozen_lm_s1_gpu0.cmd",
                "outputs/logs/schema_lp_frozen_lm_s1_gpu0.log",
                "outputs/schema_sweep/lp_frozen_lm_s1_state_only/metrics_final.json",
                "outputs/schema_sweep/lp_frozen_lm_s1_state_only/best.pt",
                "outputs/schema_sweep/lp_frozen_lm_s1_state_only/final.pt",
                "outputs/schema_sweep/lp_frozen_lm_s1_state_only/step_3000.pt",
            ],
            "Formal frozen-LM S1 LP completed with EXITCODE 0; final macro_auc is 0.798542, best-loss step 2800 macro_auc is 0.793706, and best-AUC step 800 macro_auc is 0.811302.",
            "Use as matched frozen-LM S1 source+LP evidence; compare with no-LM S1 LP and S2/S3 rows in the consolidated schema table.",
            "Stop if S1 LP metrics are merged with 12-label source loss or if metric direction is inferred without checking the table.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_FROZEN_LM_S2_FORMAL_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run",
            [
                "scripts/run_schema_frozen_lm_s2_source_gpu0.cmd",
                "scripts/summarize_frozen_lm_source_training.py",
                "outputs/logs/schema_frozen_lm_s2_source_gpu0.log",
                "outputs/final_tables/frozen_lm_source_training_summary.csv",
                "outputs/final_tables/frozen_lm_source_val_loss_trace.csv",
                "outputs/schema_sweep/frozen_lm_s2_state_answerability/checkpoints/best.pt",
                "outputs/schema_sweep/frozen_lm_s2_state_answerability/checkpoints/final.pt",
                "outputs/schema_sweep/frozen_lm_s2_state_answerability/checkpoints/step_10000.pt",
            ],
            "Formal frozen-LM S2 state_answerability source run completed with EXITCODE 0; checkpoint best_val_loss is 0.026451 at step 10000 after 8:16:39.",
            "Use with the separately recorded frozen-LM S2 LP row; do not report source loss as downstream LP/classification evidence.",
            "Stop if this source checkpoint is reported as downstream LP/classification evidence.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_FROZEN_LM_S2_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_schema_lp_frozen_lm_s2_gpu0.cmd",
                "outputs/logs/schema_lp_frozen_lm_s2_gpu0.log",
                "outputs/schema_sweep/lp_frozen_lm_s2_state_answerability/metrics_final.json",
                "outputs/schema_sweep/lp_frozen_lm_s2_state_answerability/best.pt",
                "outputs/schema_sweep/lp_frozen_lm_s2_state_answerability/final.pt",
                "outputs/schema_sweep/lp_frozen_lm_s2_state_answerability/step_3000.pt",
            ],
            "Formal frozen-LM S2 LP completed with EXITCODE 0; final macro_auc is 0.791259, best-loss step 2800 macro_auc is 0.790000, and best-AUC step 800 macro_auc is 0.816739.",
            "Use as matched frozen-LM S2 source+LP evidence; compare with S1/S3 rows in the consolidated schema table.",
            "Stop if this focused S2 result is described as a completed S1/S2/S3 schema sweep.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_FROZEN_LM_S3_FORMAL_SOURCE_RUN",
            "Phase 1",
            "completed_formal_source_run_with_resume",
            [
                "scripts/run_schema_frozen_lm_s3_source_gpu0.cmd",
                "scripts/run_schema_frozen_lm_s3_source_resume8000_gpu0.cmd",
                "scripts/summarize_frozen_lm_source_training.py",
                "outputs/logs/schema_frozen_lm_s3_source_gpu0.log",
                "outputs/logs/schema_frozen_lm_s3_source_resume8000_gpu0.log",
                "outputs/final_tables/frozen_lm_source_training_summary.csv",
                "outputs/final_tables/frozen_lm_source_val_loss_trace.csv",
                "outputs/schema_sweep/frozen_lm_s3_state_uncertainty/checkpoints/best.pt",
                "outputs/schema_sweep/frozen_lm_s3_state_uncertainty/checkpoints/final.pt",
                "outputs/schema_sweep/frozen_lm_s3_state_uncertainty/checkpoints/step_10000.pt",
            ],
            "Formal frozen-LM S3 state_uncertainty source run completed via resume after an external ^C interruption; checkpoint best_val_loss is 0.030576 at step 10000.",
            "Use with the separately recorded frozen-LM S3 LP row; keep the original interrupted log as failure provenance.",
            "Stop if this source checkpoint is reported as downstream LP/classification evidence or if the interrupted first log is hidden.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_FROZEN_LM_S3_LP_FORMAL_RUN",
            "Phase 1",
            "completed_formal_lp_run",
            [
                "scripts/run_schema_lp_frozen_lm_s3_gpu0.cmd",
                "outputs/logs/schema_lp_frozen_lm_s3_gpu0.log",
                "outputs/schema_sweep/lp_frozen_lm_s3_state_uncertainty/metrics_final.json",
                "outputs/schema_sweep/lp_frozen_lm_s3_state_uncertainty/best.pt",
                "outputs/schema_sweep/lp_frozen_lm_s3_state_uncertainty/final.pt",
                "outputs/schema_sweep/lp_frozen_lm_s3_state_uncertainty/step_3000.pt",
            ],
            "Formal frozen-LM S3 LP completed with EXITCODE 0; final macro_auc is 0.818757, best-loss step 2800 macro_auc is 0.820780, and best-AUC step 800 macro_auc is 0.824851.",
            "Use as matched frozen-LM S3 source+LP evidence; compare with S1/S2 rows in the consolidated schema table.",
            "Stop if S3 LP metrics are merged with 12-label source loss or if this focused S3 pair is described as a completed S1/S2/S3 schema sweep.",
        ),
        row(
            "P1_SCHEMA_COMPLEXITY_DIAGNOSTIC_CONSOLIDATION",
            "Phase 1",
            "completed_diagnostic_summary",
            [
                "scripts/summarize_schema_complexity_diagnostics.py",
                "outputs/final_tables/schema_complexity_diagnostic_summary.csv",
                "outputs/final_tables/schema_complexity_diagnostic_summary.md",
            ],
            "Current schema-complexity evidence has no-LM and frozen-LM S1/S2/S3 formal source+LP rows complete under the fixed split.",
            "Use as the completed formal schema-complexity table; interpret benefit direction from metric rows rather than assuming frozen-LM dominance.",
            "Stop if source-loss rows are compared directly to LP macro-AUC rows or if debug rows are treated as formal metrics.",
        ),
        row(
            "REVISION_EXECUTION_COMPLETION_GAP_AUDIT",
            "Phase 0-4",
            "completed_gap_audit",
            [
                "scripts/summarize_revision_completion_gap_audit.py",
                "outputs/final_tables/revision_completion_gap_audit.csv",
                "outputs/final_tables/revision_completion_gap_audit.md",
            ],
            "Current non-training revision packet and fixed-split formal schema sweep are complete; original full-scope data scaling remains partial because matched 10k no-LM/frozen-LM and 30k rows are not run.",
            "Continue one data-scaling row at a time only if literal full-matrix completion is required; otherwise use the current claim-boundary packet.",
            "Stop if the project is declared fully complete while original full-matrix gaps are still unresolved.",
        ),
        row(
            "P1_LLM_FAILURE_CASE_MINING_PREFLIGHT_AND_EXPORT",
            "Phase 1",
            "completed_eval_only_failure_mining",
            [
                "scripts/export_failure_mining_predictions.py",
                "outputs/failure_cases/lp_failure_mining_predictions.csv",
                "outputs/failure_cases/frozen_better_than_no_lm.csv",
                "outputs/failure_cases/no_lm_better_than_frozen.csv",
                "outputs/failure_cases/all_methods_fail.csv",
                "outputs/failure_cases/random_lm_failure_examples.csv",
                "outputs/final_tables/failure_case_summary.csv",
                "outputs/final_tables/failure_case_summary.md",
                "outputs/final_tables/failure_case_manifest.json",
            ],
            "Eval-only sample-level mining is now available; frozen-LM and no-LM fix similar numbers of each other's binary-field errors, so this does not strongly motivate immediate P2 module work.",
            "Use this in Phase 4 LLM-necessity and module-candidate synthesis; keep P2 modules deferred unless a focused paper need appears.",
            "Stop if null/uncertain rows are treated as binary correctness or if this export is described as retraining.",
        ),
        row(
            "PHASE4_REVISION_SYNTHESIS",
            "Phase 4",
            "completed_claim_synthesis",
            [
                "scripts/summarize_phase4_revision_synthesis.py",
                "outputs/final_tables/llm_necessity.csv",
                "outputs/final_tables/llm_necessity.md",
                "outputs/final_tables/module_candidates.csv",
                "outputs/final_tables/module_candidates.md",
                "outputs/final_tables/phase4_writing_claim_checklist.md",
            ],
            "Final claim-control tables now frame the revision as UMS/schema-first with limited frozen-LM use cases and deferred P2 modules.",
            "Use these tables for paper rewrite; update any older prose that described 10k/30k data scaling as unresolved.",
            "Stop if the synthesis hides the 1k frozen-LM source early-stop caveat or presents deferred modules as completed.",
        ),
        row(
            "P1_RUNTIME_REPAIR_AND_AUDIT",
            "Phase 1",
            "runtime_available_but_slow",
            [
                "outputs/logs/importtime_torch.log",
                "outputs/logs/importtime_torchvision.log",
                "outputs/logs/importtime_timm.log",
                "outputs/logs/importtime_train_vit_baseline_help.log",
            ],
            "No dependency download needed; CUDA torch/timm imports work but are slow on Windows. Git artifact scanning was mitigated.",
            "Use PATH Python 3.12 CUDA env; tolerate 30-60s startup for training entry checks.",
            "Stop if import raises an exception, leaves a Python process, or Git resumes huge add/diff scans.",
        ),
        row(
            "P2_NEW_MODULES",
            "Phase 2",
            "deferred",
            [],
            "No new SPD variants should be pursued before frozen-LM use case, UMS/schema, answerability, and serialization dependency are resolved.",
            "Only revisit after Phase 1 evidence identifies a concrete failure mode.",
            "Stop if work drifts into SPD variants without evidence need.",
        ),
    ]

    columns = [
        "task_id",
        "phase",
        "status",
        "evidence_present",
        "evidence",
        "current_claim",
        "next_action",
        "stop_condition",
    ]
    FINAL_DIR.mkdir(parents=True, exist_ok=True)
    write_csv(FINAL_DIR / "revision_execution_status.csv", rows, columns)

    text = "# Revision Execution Status\n\n"
    text += "This status sync is file/provenance based and does not import torch or start training.\n\n"
    text += markdown_table(rows, columns)
    text += "\n## Immediate Queue Boundary\n\n"
    text += (
        "- Do not run the full Phase 1 matrix at once.\n"
        "- No active training is running after the 30k frozen-LM UMS source+LP rows completed with EXITCODE 0.\n"
        "- The interrupted frozen-LM UMS 1k source run is not a normal completed run; "
        "best.pt is accepted only under documented early-stop provenance.\n"
        "- Frozen-LM UMS 1k LP and matched no-LM UMS 1k LP are complete and consolidated.\n"
        "- The 3k, 10k, and 30k no-LM/frozen-LM matched LP branches are complete; "
        "the named 30k split contains 29000 train records.\n"
        "- The 1k matched LP result is negative for frozen-LM necessity on macro-AUC; "
        "the 3k final LP macro-AUC delta favors frozen-LM modestly, but best-AUC policy still favors no-LM.\n"
        "- S2 state_answerability and S3 state_uncertainty frozen-LM debug entries passed; "
        "no-LM S2/S3 explicit auxiliary-head debug entries also passed.\n"
        "- no-LM S2/S3 schema complexity now has exported derived diagnostics; "
        "comparative claims must separate legacy derived diagnostics from explicit-head debug evidence.\n"
        "- Schema-complexity evidence is consolidated with no-LM and frozen-LM S1/S2/S3 formal source+LP rows complete under the fixed split.\n"
        "- Eval-only failure-case mining is complete; frozen-LM does not dominate no-LM in disagreement counts.\n"
        "- Phase 4 synthesis is complete: `llm_necessity.csv`, `module_candidates.csv`, and claim/writing checklist.\n"
        "- SPD new variants remain out of scope.\n"
    )
    (FINAL_DIR / "revision_execution_status.md").write_text(text, encoding="utf-8")
    print(f"Wrote {len(rows)} rows to {FINAL_DIR.relative_to(ROOT).as_posix()}")


if __name__ == "__main__":
    main()
